openapi: 3.0.3
info:
  title: "Car Marketplace ${VERSION_APP}"
  description: This is a place where sellers and buyers meat each other
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: ad
    description: Объявление (о покупке или продаже автомобилей)
paths:
  /ad/create:
    post:
      tags:
        - ad
      summary: Create ad
      operationId: adCreate
      requestBody:
        description: Request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdCreateRequest'
        required: true
      responses:
        '200':
          description: Advertisement created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdCreateResponse'

  /ad/get:
    post:
      tags:
        - ad
      summary: Get ad by ID
      operationId: getAdById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdGetRequest'
      responses:
        '200':
          description: Advertisement found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdGetResponse'

  /ad/search:
    post:
      tags:
        - ad
      summary: Search ad with filters
      operationId: searchAds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdSearchRequest'
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdSearchResponse'

  /ad/update:
    post:
      tags:
        - ad
      summary: Update advertisement
      operationId: updateAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdUpdateRequest'
      responses:
        '200':
          description: Advertisement updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdUpdateResponse'
  /ad/delete:
    post:
      tags:
        - ad
      summary: Delete advertisement
      operationId: deleteAd
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdDeleteRequest'
      responses:
        '200':
          description: Advertisement deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdDeleteResponse'



components:
  schemas:
    Stub:
      type: string
      enum: [NONE, SUCCESS, NOT_FOUND, BAD_ID, BAD_TITLE, BAD_DESCRIPTION, CANNOT_DELETE, BAD_SEARCH_STRING, DB_ERROR]
      default: SUCCESS
      example: SUCCESS
      nullable: true
    WorkMode:
      type: string
      enum: [TEST, PROD, STUB]
      default: TEST
      example: TEST
      nullable: true
    # Request schemas
    IRequest:
      type: object
      description: Базовый интерфейс для всех запросов
      properties:
        requestType:
          type: string
          description: Поле-дескриминатор для вычисления типа запроса
          example: create
        workMode:
          $ref: '#/components/schemas/WorkMode'  # ← Ссылка на общий enum
        stub:
          $ref: '#/components/schemas/Stub'

      discriminator:
        propertyName: requestType
        mapping:
          create: '#/components/schemas/AdCreateRequest'
          get: '#/components/schemas/AdGetRequest'
          update: '#/components/schemas/AdUpdateRequest'
          delete: '#/components/schemas/AdDeleteRequest'
          search: '#/components/schemas/AdSearchRequest'
      # Базовый response для всех ответов
    BaseResponse:
      type: object
      properties:
        responseType:
          type: string
        result:
          $ref: '#/components/schemas/ResponseResult'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        timestamp:
          type: string
          format: date-time
          example: "2023-10-05T14:30:00Z"
      discriminator:
        propertyName: responseType
        mapping:
          create: '#/components/schemas/AdCreateResponse'
          get: '#/components/schemas/AdGetResponse'
          update: '#/components/schemas/AdUpdateResponse'
          delete: '#/components/schemas/AdDeleteResponse'
          search: '#/components/schemas/AdSearchResponse'
    AdLock:
      type: string
      description: Версия оптимистичной блокировки
    # Request schemas
    AdCreateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          required:
            - title
            - description
            - price
            - carInfo
          properties:
            title:
              type: string
              minLength: 5
              maxLength: 200
              example: "Toyota Camry 2018 года"
            description:
              type: string
              minLength: 10
              maxLength: 2000
              example: "Автомобиль в отличном состоянии"
            price:
              type: number
              format: double
              minimum: 0
              example: 1500000.0
            carInfo:
              $ref: '#/components/schemas/CarInfo'
            location:
              type: string
              example: "Москва"
            contactPhone:
              type: string
              example: "+79991234567"

    AdGetRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
              minimum: 1
              example: 123

    AdSearchRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          properties:
            brand:
              type: string
              example: "Toyota"
            model:
              type: string
              example: "Camry"
            minYear:
              type: integer
              minimum: 1990
              maximum: 2025
              example: 2015
            maxYear:
              type: integer
              minimum: 1990
              maximum: 2030
              example: 2025
            minPrice:
              type: number
              format: double
              minimum: 0
              example: 1000000.0
            maxPrice:
              type: number
              format: double
              minimum: 0
              example: 2000000.0
            page:
              type: integer
              example: 0
            size:
              type: integer
              example: 20
            location:
              type: string
              example: "Москва"

    AdUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
            lock:
              $ref: '#/components/schemas/AdLock'
            title:
              type: string
              minLength: 5
              maxLength: 200
            description:
              type: string
              minLength: 10
              maxLength: 200
            price:
              type: number
              format: double
              minimum: 0
            carInfo:
              $ref: '#/components/schemas/CarInfo'
            status:
              $ref: '#/components/schemas/AdStatus'
            location:
              type: string
              example: "Москва"
            contactPhone:
              type: string
              example: "+79991234567"

    AdDeleteRequest:
      allOf:
        - $ref: '#/components/schemas/IRequest'
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              format: int64
            lock:
              $ref: '#/components/schemas/AdLock'

    # Response schemas
    Error:
      type: object
      properties:
        code:
          type: string
          example: "VALIDATION_ERROR"
        group:
          type: string
          example: "field_validation"
        field:
          type: string
          example: "price"
        message:
          type: string
          example: "Price must be positive"
    ResponseResult:
      type: string
      enum:
        - success
        - error

    AdStatus:
      type: string
      enum: [ DRAFT, ACTIVE, SOLD, ARCHIVED ]
      example: "ACTIVE"
    # Специфичные ответы для каждой операции
    AdCreateResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/AdData'
            adId:
              type: integer
              format: int64

    AdGetResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/AdData'

    AdSearchResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            ads:
              type: array
              items:
                $ref: '#/components/schemas/AdData'
            total:
              type: integer
              description: Общее количество найденных объявлений
            page:
              type: integer
              description: Текущая страница
            size:
              type: integer
              description: Размер страницы
            totalPages:
              type: integer
              description: Общее количество страниц
            hasNext:
              type: boolean
              description: Есть ли следующая страница
            hasPrevious:
              type: boolean
              description: Есть ли предыдущая страница
            searchId:
              type: string
              description: ID поискового запроса для кэширования

    AdUpdateResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            ad:
              $ref: '#/components/schemas/AdData'
            previousVersion:
              $ref: '#/components/schemas/AdData'

    AdDeleteResponse:
      allOf:
        - $ref: '#/components/schemas/BaseResponse'
        - type: object
          properties:
            deletedAdId:
              type: integer
              format: int64
            deletionTime:
              type: string
              format: date-time

    # Общие данные
    AdData:
      type: object
      properties:
        id:
          type: integer
          format: int64
        lock:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
          format: double
        carInfo:
          $ref: '#/components/schemas/CarInfo'
        status:
          $ref: '#/components/schemas/AdStatus'
        location:
          type: string
        contactPhone:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        viewsCount:
          type: integer
          description: Количество просмотров
        favoriteCount:
          type: integer
          description: Количество добавлений в избранное



    # Common models
    EngineType:
      type: string
      enum: [GASOLINE, DIESEL, ELECTRIC, HYBRID]
      example: "GASOLINE"
    Transmission:
      type: string
      enum: [MANUAL, AUTOMATIC, ROBOT, VARIATOR]
      example: "MANUAL"
    CarInfo:
      type: object
      required:
        - brand
        - model
        - year
      properties:
        brand:
          type: string
          example: "Toyota"
        model:
          type: string
          example: "Camry"
        year:
          type: integer
          minimum: 1990
          maximum: 2025
          example: 2018
        mileage:
          type: integer
          minimum: 0
          example: 75000
        color:
          type: string
          example: "Черный"
        engineType:
          $ref: '#/components/schemas/EngineType'
        engineVolume:
          type: number
          format: double
          minimum: 0.5
          maximum: 8.0
          example: 2.5
        horsePower:
          type: integer
          format: int32
          minimum: 50
          example: 181
        transmission:
          $ref: '#/components/schemas/Transmission'